### ISSUE TITLE
Git: Clicking on "Diff" creates traceback

### ISSUE THREAD

**Issue by hkienle** [yorikvanhavre/WebTools#14]
The UI tries to issue `git diff afile.FCStd` but fails:

```
fatal: unable to read files to diff'
Traceback (most recent call last):
  File "/home/xxx/.FreeCAD/Mod/WebTools/Git.py", line 119, in getDiff
    textform.browserText.setPlainText(self.repo.git.diff(f))
  File "/tmp/.mount_freecao4tWBj/usr/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/tmp/.mount_freecao4tWBj/usr/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/tmp/.mount_freecao4tWBj/usr/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git diff cube.FCStd
  stderr: 'ImportError: No module named site
fatal: unable to read files to diff'
```
I have the most recent version of WebTools according to the Addon manager.

OS: PureOS (GNOME/gnome-xorg)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23323 (Git) AppImage
Build type: Release
Branch: master
Hash: 512d5c6141aec52b6eecc67370336a28fde862a6
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by yorikvanhavre** [comment]
Sorry for the delay! Should be fixed now
