### ISSUE TITLE
WebTools embeds an obsolete version of requests

### ISSUE THREAD

**Issue by trougnouf** [yorikvanhavre/WebTools#15]
Trying to open the workbench on Arch Linux yields the following error message:
```
18:14:33  module 'collections' has no attribute 'MutableMapping'
18:14:33  Traceback (most recent call last):
  File "<string>", line 34, in Initialize
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/trougnouf/.FreeCAD/Mod/WebTools/Sketchfab.py", line 29, in <module>
    import FreeCAD, os, zipfile, requests, tempfile, json, time, re
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/trougnouf/.FreeCAD/Mod/WebTools/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/trougnouf/.FreeCAD/Mod/WebTools/requests/utils.py", line 30, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/trougnouf/.FreeCAD/Mod/WebTools/requests/cookies.py", line 174, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
```
In Python 3.3 'MutableMapping' was moved from collections to [collections.abc](https://docs.python.org/3/library/collections.abc.html#module-collections.abc).

WebTools embeds an obsolete version of requests. Simply deleting it with `rm .FreeCAD/Mod/WebTools/requests/ -rf` seems to bring functionality.

BIMServer.py already has a catch which seems to be a better solution than creating (un)maintenance work and likely security holes.
```
        try:
            import requests
        except:
            FreeCAD.Console.PrintError(translate("WebTools","requests python module not found, aborting. Please install python-requests\n"))
            return
```

**Comment by trougnouf** [comment]
Note that I had to enter my private key's password in the terminal used to open FreeCAD; there was otherwise no indication of a prompt and it just didn't seem to work.
